var tableauQuestion = [
    {   question : "Wenn du 75 kmh fährst und zu einem Wohnort kommst, was tust du?:",
        propositionA : "Du beschleunigst",
        propositionB : "Du behälst deine Geschwindigkeit, wenn du niemanden überholst",
        propositionC : "Du wirst langsamer",
        propositionD : "Du behälst deine Geschwindigkeit",
        reponse : "C"},

    {   question : "Wenn du an einer Ampel rechts abbiegst, aber jemanden über die Straße laufen siehst, tust du?:",
        propositionA : "Du fährst an der Person vorbei",
        propositionB : "Du schaust ob keine anderen Fahrzeuge in der Nähe sind",
        propositionC : "Du wartest bis die Person auf der anderen Straßenseite angekommen ist",
        propositionD : "Du erschießt die Person und fährst weiter",
        reponse : "C"},

    {   question : "Ohne andere Ankündigung, die Geschwindigkeit in einem Wohnort ist : __ kmh",
        propositionA : "70",
        propositionB : "80",
        propositionC : "30",
        propositionD : "90",
        reponse : "A"},

  {   question : "Vor jedem Fahrbahnwechsel ist zu beachten:",
        propositionA : "In die Rückspiegel schauen",
        propositionB : "Den toten Winkel zu prüfen",
        propositionC : "Deine Intention anzuzeigen (blinken)",
        propositionD : "Alles davon",
        reponse : "D"},

  {   question : "Welcher Alkoholpegel gilt als Fahren unter Alkoholeinfluss?",
        propositionA : "0.05%",
        propositionB : "0.18%",
        propositionC : "0.08%",
        propositionD : "0.06%",
        reponse : "C"},

  {   question : "Wann kannst du an einer Ampel weiterfahren?",
        propositionA : "Wenn es Grün ist",
        propositionB : "Wenn nix los ist",
        propositionC : "Wenn du in einer Schulzone bist",
        propositionD : "Wenn es Grün ist und / oder rechts und du rechts abbiegst",
        reponse : "D"},

  {   question : "Ein Passant hat ein rote Ampel, was tust du?",
        propositionA : "Du lässt ihn vorbei",
        propositionB : "Du prüfst bevor du weiterfährst",
        propositionC : "Du winkst ihn vorbei",
        propositionD : "Du fährst weiter, weil du grün hast",
        reponse : "D"},

  {   question : "Was ist beim Überholen erlaubt?",
        propositionA : "Du fährst dicht auf und ballerst mit 200 kmh raus",
        propositionB : "Du überholst ohne die Straße zu verlassen",
        propositionC : "Du fährst kurz auf der Gegenspur um zu überholen",
        propositionD : "Du fährst durch ihn durch",
        reponse : "C"},

  {   question : "Du fährst auf einer Autobahn mit einer Geschwindigkeitsbegrenzung von 180 kmh. Die meisten fahren 190kmh, also fährst du?:",
        propositionA : "150 kmh",
        propositionB : "170 kmh",
        propositionC : "190 kmh",
        propositionD : "180 kmh",
        reponse : "D"},

  {   question : "Wenn du überholt wirst, ist es wichtig NICHT:",
        propositionA : "Langsamer zu werden",
        propositionB : "In deine Spiegel zu gucken",
        propositionC : "Den Fahrer böse anzuschauen",
        propositionD : "Gas geben um es ihm zu zeigen",
        reponse : "D"},
]
